/**
 * DEPRECATED:
 *
 * Use SCREEN.SHOW
 */
const SHOW = {
    INK: 'INK',
    FORTUNE: 'FORTUNE',
    D8TE_NIGHT: 'D8TE_NIGHT',
    FLASHBACK: 'FLASHBACK',
    HOLIC: 'HOLIC',
    AWAKENING: 'AWAKENING',
    PHASES: 'PHASES',
    UNCONDITIONAL: 'UNCONDITIONAL',
    HIDDEN_KISSES: 'HIDDEN_KISSES',
    SILK_N_SPICE: 'SILK_N_SPICE'
};

export default SHOW;